export const POST_SIGN_IN = "POST_SIGN_IN";
export const POST_SIGN_IN_SUCCESS = "POST_SIGN_IN_SUCCESS";
export const POST_SIGN_IN_ERROR = "POST_SIGN_IN_ERROR";

export const POST_SIGN_OUT = "POST_SIGN_OUT";
export const POST_SIGN_OUT_SUCCESS = "POST_SIGN_OUT_SUCCESS";
export const POST_SIGN_OUT_ERROR = "POST_SIGN_OUT_ERROR";
